version: '3.7'
services:

  tests:
    build: ./backend
    command: bash -c "make bar-tests"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    profiles:
      - test

  frontend-build:
    image: node:20
    container_name: frontend-build
    working_dir: /app
    command: bash -c "npm install && npm run build && npm install -g serve && serve -s dist -l 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - build

  backend:
    build: ./backend
    command: bash -c "make bar"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: frontend-container
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
networks:
  app-network:
    driver: bridge
